# Site settings
title: "Theophilus Malel"
email: "theophilusmalel@gmail.com"
description: >-
  A highly skilled Network Security Engineer with extensive experience in Fortinet technologies, firewall configurations, SD-WAN, endpoint security, VPNs, and cybersecurity projects.
  Proven expertise in securing enterprise infrastructure, leading national security deployments, and continuously staying updated with modern security solutions.

minimal_mistakes_skin: dark
search: true
timezone: Africa/Nairobi
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes"

# Output
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/

# Includes
include:
  - _pages

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-remote-theme

# Author info (for sidebar)
author:
  name   : "Theophilus Malel"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Network Security Engineer | Fortinet Specialist | Cybersecurity Leader | Ethical Hacker"
  location : "Nairobi, Kenya"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/theophilusmalel"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/theophilusmalel"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:theophilusmalel@gmail.com"

# Footer links
footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/theophilusmalel"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/theophilusmalel"

# Defaults
defaults:
  # Home page
  - scope:
      path: ""
      type: "pages"
    values:
      layout: home
      author_profile: true

  # Posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

# Archive settings
category_archive:
  type: liquid
  path: /categories/

tag_archive:
  type: liquid
  path: /tags/
