# Site settings
title: "Theophilus Malel"
email: "theophilusmalel@gmail.com"
description: >-
  A highly skilled Network Security Engineer with extensive experience in Fortinet technologies, firewall configurations, SD-WAN, endpoint security, VPNs, and cybersecurity projects.
  Proven expertise in securing enterprise infrastructure, leading national security deployments, and continuously staying updated with modern security solutions.

baseurl: "" # leave empty for user.github.io
url: "https://theophilusmalel.github.io" # your GitHub Pages URL

# Theme
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: dark
search: true
timezone: Africa/Nairobi
markdown: kramdown

# Author profile (for sidebar)
author:
  name   : "Theophilus Malel"
  avatar : "/assets/images/theoo.jpg"
  bio    : "Network Security Engineer | Fortinet Specialist | Cybersecurity Leader"
  location: "Nairobi, Kenya"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/theophilusmalel"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/theophilusmalel"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:theophilusmalel@gmail.com"

# Footer links
footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/theophilusmalel"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/theophilusmalel"

# Pagination
paginate: 5
paginate_path: /page:num/
permalink: /:categories/:title/

# Include custom pages
include:
  - _pages

# Plugins (GitHub Pages supported)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-remote-theme

# Defaults to enable layout and author sidebar globally
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: home
      author_profile: true

  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

# Archives (optional)
category_archive:
  type: liquid
  path: /categories/

tag_archive:
  type: liquid
  path: /tags/
