# Site settings
title: "Theophilus Malel"
email: "Theophilusmalel@gmail.com"
description: >-
  A highly skilled Network Security Engineer with extensive experience in Fortinet technologies, firewall configurations, SD-WAN, endpoint security, VPNs, and cybersecurity projects. 
  Proven expertise in securing enterprise infrastructure, leading national security deployments, and continuously staying updated with modern security solutions.

github_username: theophilusmalel
minimal_mistakes_skin: dark
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

# Outputting
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: Africa/Nairobi

include:
  - _pages

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-remote-theme

author:
  name   : "Theophilus Malel"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Network Security Engineer | Fortinet Specialist | Cybersecurity Leader | CyberSecurity Consultant | Ethical Hacker"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/theophilusmalel"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/theophilusmalel"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:theophilusmalel@gmail.com"

footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/theophilusmalel"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/theophilusmalel"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/

tag_archive:
  type: liquid
  path: /tags/
